### ISSUE TITLE
Jobs.clear(state, name) is failing - TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by ScottAgirs** [msavin/SteveJobs..meteor.jobs.scheduler.queue.background.tasks#66]
I am trying to remove Jobs from queue with the .clear method, but it is failing with the error (screenshot below)

**Here is the snippet I use:**
```
import { Jobs } from "meteor/msavin:sjobs";

var state = "failure";
var name = "poToTeacher"; // this name is the value in database
Jobs.clear(state, name);
..
```
![screen shot 2018-09-25 at 16 07 58](https://user-images.githubusercontent.com/11737572/46040013-35ef9800-c0dd-11e8-9067-ec5543389212.jpg)

**Comment by msavin** [comment]
@ScottAgirs thanks for reporting htis - should be fixed in 3.1. If it persists, please let me know.

**Comment by OliverColeman** [comment]
Just updated to 3.1.1, still seeing this issue. I'm calling `Jobs.clear('success');`
I seem to have three collections for Jobs:  `db.jobs_data`, `db.jobs_dominator`, `db.jobs_dominator_3`.
